const LEVELS = [
  {
    "id": 1,
    "name": "Tendre",
    "desc": "Doux et mignon — pour dire bonjour",
    "color": "#a9c9b8",
    "dares": [
      "Envoie un vocal où tu me dis bonjour avec la voix la plus douce que tu as.",
      "Envoie un vocal où tu me dis un petit mot doux inventé sur le moment.",
      "Envoie un vocal où tu me dis ce que tu as prévu de faire aujourd'hui.",
      "Envoie un vocal où tu me dis ta citation ou pensée du jour.",
      "Envoie un vocal où tu me dis un vieux souvenir qui te fait sourire.",
      "Envoie un vocal où tu me dis ce que tu ressens en pensant à moi là maintenant.",
      "Envoie un vocal où tu me dis un compliment tout simple.",
      "Envoie un vocal où tu me dis comment s'est passée ta journée.",
      "Envoie un vocal où tu me dis ta chanson du moment, fredonnée.",
      "Envoie un vocal où tu me dis un « je pense à toi » tout doux.",
      "Envoie un vocal où tu me dis trois mots qui décrivent ton humeur.",
      "Envoie un vocal où tu me dis un vœu ou souhait pour nous deux.",
      "Envoie un vocal où tu me dis ce que tu aimerais qu'on fasse ce week-end.",
      "Envoie un vocal où tu me dis un souvenir léger de notre dernière conversation.",
      "Envoie une photo de ce que tu vois par ta fenêtre là, maintenant.",
      "Envoie une photo de ta boisson chaude ou froide du moment.",
      "Envoie une photo de tes chaussures du jour.",
      "Envoie une photo de ton bureau ou ta table de travail.",
      "Envoie une photo de le ciel, tel qu'il est maintenant.",
      "Envoie une photo de ton endroit préféré chez toi.",
      "Envoie une photo de un objet qui te fait penser à moi.",
      "Envoie une photo de ta tasse ou ton verre préféré.",
      "Envoie une photo de ton dernier repas ou en-cas.",
      "Envoie une photo de un coin de ta chambre.",
      "Envoie une photo de quelque chose que tu trouves joli aujourd'hui.",
      "Envoie une photo de ta main, posée sur une table.",
      "Envoie une photo de ton carnet ou tes notes du jour.",
      "Envoie une photo de ta playlist ouverte sur ton téléphone.",
      "Décris ta journée en 3 emojis seulement.",
      "Décris ton humeur du moment en 3 emojis seulement.",
      "Décris ce que tu ressens pour moi là en 3 emojis seulement.",
      "Décris ta semaine jusqu'ici en 3 emojis seulement.",
      "Décris ce que tu as mangé aujourd'hui en 3 emojis seulement.",
      "Décris ton dernier film ou série vus en 3 emojis seulement.",
      "Décris ta météo intérieure en 3 emojis seulement.",
      "Décris notre dernière conversation en 3 emojis seulement.",
      "Décris ton réveil ce matin en 3 emojis seulement.",
      "Décris ce que tu espères pour ce soir en 3 emojis seulement.",
      "Décris notre relation en ce moment en 3 emojis seulement.",
      "Décris ton dimanche idéal en 3 emojis seulement.",
      "Décris ta to-do list du jour en 3 emojis seulement.",
      "Raconte le tout premier souvenir qui te vient en pensant à moi.",
      "Raconte un souvenir d'enfance qui te fait sourire.",
      "Raconte ta meilleure sortie récente.",
      "Raconte ce qui t'a fait rire aujourd'hui.",
      "Raconte un petit rituel que tu aimes dans ta journée.",
      "Raconte ton endroit préféré au monde et pourquoi.",
      "Raconte une chose que tu as apprise récemment.",
      "Raconte ton dernier fou rire.",
      "Raconte un souvenir avec moi qui te réchauffe le cœur.",
      "Raconte ta plus belle surprise de la semaine.",
      "Raconte un détail que tu aimes chez toi-même.",
      "Raconte ce que tu ferais si tu avais une heure de libre là.",
      "Raconte ton meilleur souvenir de vacances.",
      "Envoie une chanson qui te fait penser à moi, sans explication.",
      "Envoie une chanson qui reflète ton humeur du moment.",
      "Envoie une chanson que tu as écoutée en boucle cette semaine.",
      "Envoie une chanson qui te donne toujours le sourire.",
      "Envoie une chanson que tu voudrais qu'on écoute ensemble.",
      "Envoie une chanson qui te rappelle un bon souvenir.",
      "Envoie une chanson parfaite pour un dimanche tranquille.",
      "Envoie une chanson qui te donne envie de danser.",
      "Envoie une chanson qui te calme quand ça va pas.",
      "Envoie une chanson de ton adolescence que tu aimes encore.",
      "Envoie une chanson qui parle un peu de nous, selon toi.",
      "Envoie une chanson que tu trouves sous-estimée.",
      "Fais-moi un compliment sincère sur un truc que je fais bien selon toi.",
      "Fais-moi un compliment sincère sur ma façon d'être avec toi.",
      "Fais-moi un compliment sincère sur mon caractère.",
      "Fais-moi un compliment sincère sur un souvenir précis de nous que tu gardes.",
      "Fais-moi un compliment sincère sur quelque chose que tu n'as jamais osé dire.",
      "Fais-moi un compliment sincère sur ma façon de te faire rire.",
      "Fais-moi un compliment sincère sur un détail chez moi que tu trouves attachant.",
      "Fais-moi un compliment sincère sur ma manière d'écrire ou de parler.",
      "Fais-moi un compliment sincère sur ce que je t'apporte au quotidien.",
      "Fais-moi un compliment sincère sur mon énergie ou ma vibe.",
      "Fais-moi un compliment sincère sur une de mes habitudes que tu aimes.",
      "Fais-moi un compliment sincère sur la façon dont je prends soin de toi.",
      "Envoie un selfie avec ton sourire le plus naturel.",
      "Envoie un selfie juste après le réveil.",
      "Envoie un selfie avec ta tenue du jour.",
      "Envoie un selfie avec ton expression la plus drôle.",
      "Envoie un selfie pris à l'instant, sans retouche.",
      "Envoie un selfie où tu montres ton humeur du moment.",
      "Envoie un selfie avec un objet que tu aimes bien.",
      "Envoie un selfie dans la lumière que tu préfères.",
      "Envoie un selfie avec ton regard le plus doux.",
      "Envoie un selfie où tu fais un clin d'œil.",
      "Envoie un selfie avec ta coiffure du jour, peu importe l'état.",
      "Envoie un selfie avec ce que tu portes là, maintenant.",
      "Dis-moi une chose pour laquelle tu es reconnaissant·e aujourd'hui, à propos de nous.",
      "Dis-moi un petit bonheur que tu as eu aujourd'hui.",
      "Dis-moi ce que tu attends avec impatience cette semaine.",
      "Dis-moi un mot qui résume ta journée.",
      "Dis-moi ce qui te fait sourire en ce moment précis.",
      "Dis-moi une qualité que tu apprécies chez toi.",
      "Dis-moi ton petit plaisir du jour.",
      "Dis-moi ce que tu ferais si tu avais une baguette magique là.",
      "Dis-moi une chose simple qui t'a rendu·e heureux·se récemment.",
      "Dis-moi ton programme idéal pour ce soir.",
      "Dis-moi un souvenir léger de la semaine.",
      "Dis-moi ce que tu ressens en lisant ce message.",
      "Envoie-moi un mot doux inventé rien que pour moi.",
      "Envoie-moi une liste de 3 choses que tu aimes chez nous.",
      "Envoie-moi un petit poème de 2 lignes.",
      "Envoie-moi ton emoji du jour et pourquoi.",
      "Envoie-moi une photo de ton carnet ou de tes notes.",
      "Envoie-moi un souvenir photo ancien de toi.",
      "Envoie-moi ta playlist du moment en une phrase.",
      "Envoie-moi un mot que tu trouves joli.",
      "Envoie-moi trois adjectifs qui te décrivent aujourd'hui.",
      "Envoie-moi une note vocale de 10 secondes, juste pour rire.",
      "Envoie-moi ton horoscope du jour, en vrai ou inventé.",
      "Envoie-moi un vœu tout simple pour notre semaine.",
      "Envoie un vocal où tu imagines notre prochaine sortie ensemble.",
      "Envoie un vocal où tu imagines un dimanche parfait à deux.",
      "Envoie un vocal où tu imagines ce qu'on ferait si on avait une journée sans contraintes.",
      "Envoie un vocal où tu imagines notre repas idéal ensemble.",
      "Envoie un vocal où tu imagines un souvenir qu'on pourrait créer bientôt.",
      "Envoie un vocal où tu imagines notre chanson si on en choisissait une.",
      "Envoie un vocal où tu imagines le cadeau parfait pour moi.",
      "Envoie un vocal où tu imagines un voyage qu'on pourrait faire un jour.",
      "Envoie un vocal où tu imagines notre routine du matin idéale.",
      "Envoie un vocal où tu imagines ce qu'on ferait un soir de pluie.",
      "Envoie un vocal où tu imagines notre pire mais plus drôle rendez-vous imaginaire.",
      "Envoie un vocal où tu imagines un projet qu'on pourrait faire à deux."
    ]
  },
  {
    "id": 2,
    "name": "Complice",
    "desc": "Un peu plus taquin, toujours léger",
    "color": "#d3c48a",
    "dares": [
      "Envoie un vocal où tu racontes un souvenir marrant de nous deux.",
      "Envoie un vocal où tu racontes la fois où tu as eu le plus honte devant moi.",
      "Envoie un vocal où tu racontes un fantasme de rendez-vous parfait, version sage.",
      "Envoie un vocal où tu racontes ce que tu ferais si je débarquais chez toi là.",
      "Envoie un vocal où tu racontes ta pire tentative de séduction ratée.",
      "Envoie un vocal où tu racontes un truc bête que tu as fait pour attirer mon attention.",
      "Envoie un vocal où tu racontes ce que tu penses vraiment de notre premier échange.",
      "Envoie un vocal où tu racontes un moment où tu as eu un coup de cœur soudain pour moi.",
      "Envoie un vocal où tu racontes ta réaction si je t'envoyais un bisou surprise là.",
      "Envoie un vocal où tu racontes ce que tu ferais si on se croisait par hasard aujourd'hui.",
      "Envoie un vocal où tu racontes l'anecdote la plus embarrassante que tu oses partager.",
      "Envoie un vocal où tu racontes ce que tu penses de notre alchimie.",
      "Décris en 5 mots exactement ce que tu ressens là, maintenant.",
      "Décris en 5 mots exactement ce que t'inspire mon prénom.",
      "Décris en 5 mots exactement notre dynamique à nous deux.",
      "Décris en 5 mots exactement ta journée idéale avec moi.",
      "Décris en 5 mots exactement ce que tu aimes dans nos discussions.",
      "Décris en 5 mots exactement ton humeur taquine du moment.",
      "Décris en 5 mots exactement ce que je te fais ressentir.",
      "Décris en 5 mots exactement notre alchimie selon toi.",
      "Décris en 5 mots exactement l'ambiance que tu voudrais ce soir.",
      "Décris en 5 mots exactement ce que tu penses de nous.",
      "Décris en 5 mots exactement ta tenue actuelle.",
      "Décris en 5 mots exactement ton état d'esprit taquin du jour.",
      "Envoie une photo de toi en train de faire un truc banal du quotidien.",
      "Envoie une photo de toi en train de préparer à manger ou à boire.",
      "Envoie une photo de toi en train de traîner sur ton canapé.",
      "Envoie une photo de toi en train de faire une grimace.",
      "Envoie une photo de toi en train de regarder par la fenêtre, pensif·ve.",
      "Envoie une photo de toi en train de faire semblant de travailler.",
      "Envoie une photo de toi en train de te déplacer dans ta maison.",
      "Envoie une photo de toi en train de prendre un moment pour toi.",
      "Envoie une photo de toi en train de faire ton activité préférée du moment.",
      "Envoie une photo de toi en train de te reposer.",
      "Envoie une photo de toi en train de sourire à la caméra sans prévenir.",
      "Envoie une photo de toi en train de faire un clin d'œil complice.",
      "Raconte ce qu'on ferait ensemble si tu débarquais chez moi dans 10 minutes.",
      "Raconte ce qu'on ferait ensemble si on avait une soirée entière rien qu'à nous.",
      "Raconte ce qu'on ferait ensemble un dimanche pluvieux, sans rien à faire.",
      "Raconte ce qu'on ferait ensemble si on partait en road trip surprise.",
      "Raconte ce qu'on ferait ensemble si on se retrouvait dans un bar ce soir.",
      "Raconte ce qu'on ferait ensemble si on avait toute une journée libre ensemble.",
      "Raconte ce qu'on ferait ensemble si on se réveillait dans la même maison demain.",
      "Raconte ce qu'on ferait ensemble en pleine nuit, sans bruit.",
      "Raconte ce qu'on ferait ensemble si on avait une soirée jeux de société qui dérape un peu.",
      "Raconte ce qu'on ferait ensemble au moment où on se reverrait enfin.",
      "Raconte ce qu'on ferait ensemble si on cuisinait ensemble ce soir.",
      "Raconte ce qu'on ferait ensemble sur un malentendu comique.",
      "Envoie ta chanson « je pense à toi » du moment, avec un mot en légende.",
      "Envoie ta chanson « je pense à toi » du moment, avec une raison de ce choix.",
      "Envoie ta chanson « je pense à toi » du moment, avec un souvenir lié à ce morceau.",
      "Envoie ta chanson « je pense à toi » du moment, avec ton passage préféré expliqué.",
      "Envoie ta chanson « je pense à toi » du moment, avec un emoji qui résume ton envie.",
      "Envoie ta chanson « je pense à toi » du moment, avec la phrase qui te fait le plus penser à moi.",
      "Envoie ta chanson « je pense à toi » du moment, avec ce que tu ferais en l'écoutant avec moi.",
      "Envoie ta chanson « je pense à toi » du moment, avec ton ambiance du moment.",
      "Envoie ta chanson « je pense à toi » du moment, avec une dédicace toute simple.",
      "Envoie ta chanson « je pense à toi » du moment, avec un indice sur ton humeur.",
      "Envoie ta chanson « je pense à toi » du moment, avec trois mots qui décrivent l'ambiance.",
      "Envoie ta chanson « je pense à toi » du moment, avec ce que ça te donne envie de faire.",
      "Imite ma façon de parler dans un vocal de 15 secondes.",
      "Imite la façon dont je ris dans un vocal de 15 secondes.",
      "Imite comment je dis bonjour le matin dans un vocal de 15 secondes.",
      "Imite comment je réagis quand je suis surpris·e dans un vocal de 15 secondes.",
      "Imite ma voix quand je suis fatigué·e dans un vocal de 15 secondes.",
      "Imite comment je te taquine d'habitude dans un vocal de 15 secondes.",
      "Imite ma façon de dire ton prénom dans un vocal de 15 secondes.",
      "Imite comment je chante sous la douche selon toi dans un vocal de 15 secondes.",
      "Imite ma réaction si tu me faisais une surprise dans un vocal de 15 secondes.",
      "Imite comment tu m'imagines au réveil dans un vocal de 15 secondes.",
      "Imite ma façon de raconter une anecdote dans un vocal de 15 secondes.",
      "Imite comment je dirais « je t'aime » selon toi dans un vocal de 15 secondes.",
      "Envoie un dessin ou un griffonnage rapide de nous deux et prends-le en photo.",
      "Envoie un dessin ou un griffonnage rapide de ce que tu ressens là et prends-le en photo.",
      "Envoie un dessin ou un griffonnage rapide d'un souvenir qu'on partage et prends-le en photo.",
      "Envoie un dessin ou un griffonnage rapide de ton animal ou objet préféré et moi et prends-le en photo.",
      "Envoie un dessin ou un griffonnage rapide de la soirée idéale ensemble et prends-le en photo.",
      "Envoie un dessin ou un griffonnage rapide de nous en super-héros et prends-le en photo.",
      "Envoie un dessin ou un griffonnage rapide de nous version dessin animé et prends-le en photo.",
      "Envoie un dessin ou un griffonnage rapide d'un endroit où tu voudrais m'emmener et prends-le en photo.",
      "Envoie un dessin ou un griffonnage rapide de ton humeur du jour et prends-le en photo.",
      "Envoie un dessin ou un griffonnage rapide de la première fois qu'on s'est parlé et prends-le en photo.",
      "Envoie un dessin ou un griffonnage rapide de nous dans dix ans, en rigolant et prends-le en photo.",
      "Envoie un dessin ou un griffonnage rapide d'un moment inventé et absurde entre nous et prends-le en photo.",
      "Envoie 3 mots qui décrivent ce que tu préfères chez moi côté caractère.",
      "Envoie 3 mots qui décrivent ta façon de flirter.",
      "Envoie 3 mots qui décrivent ce que tu ressens quand on se taquine.",
      "Envoie 3 mots qui décrivent ton style de séduction.",
      "Envoie 3 mots qui décrivent ce que tu aimes dans notre complicité.",
      "Envoie 3 mots qui décrivent ta réaction quand je te surprends.",
      "Envoie 3 mots qui décrivent l'ambiance de nos conversations.",
      "Envoie 3 mots qui décrivent ce que tu ressens juste avant qu'on se voie.",
      "Envoie 3 mots qui décrivent ton humeur taquine actuelle.",
      "Envoie 3 mots qui décrivent ce que tu trouves attirant chez moi.",
      "Envoie 3 mots qui décrivent notre alchimie en général.",
      "Envoie 3 mots qui décrivent ce que tu ressens quand je te complimente.",
      "Raconte ton fantasme de rendez-vous parfait avec moi, version sage.",
      "Raconte ton fantasme de rendez-vous parfait avec moi, version aventure.",
      "Raconte ton fantasme de rendez-vous parfait avec moi, version cocooning.",
      "Raconte ton fantasme de rendez-vous parfait avec moi, version originale, jamais tentée avant.",
      "Raconte ton fantasme de rendez-vous parfait avec moi, avec un lieu précis en tête.",
      "Raconte ton fantasme de rendez-vous parfait avec moi, avec une tenue précise pour chacun.",
      "Raconte ton fantasme de rendez-vous parfait avec moi, avec une activité insolite.",
      "Raconte ton fantasme de rendez-vous parfait avec moi, qui se termine en fou rire.",
      "Raconte ton fantasme de rendez-vous parfait avec moi, version voyage improvisé.",
      "Raconte ton fantasme de rendez-vous parfait avec moi, version soirée à la maison.",
      "Raconte ton fantasme de rendez-vous parfait avec moi, version grande première fois.",
      "Raconte ton fantasme de rendez-vous parfait avec moi, en trois étapes précises.",
      "Envoie-moi un surnom coquin que tu voudrais utiliser pour moi.",
      "Envoie-moi une private joke qu'on pourrait créer.",
      "Envoie-moi ton emoji préféré pour me taquiner.",
      "Envoie-moi un compliment déguisé en pique gentille.",
      "Envoie-moi une phrase d'accroche que tu utiliserais sur moi si on se rencontrait aujourd'hui.",
      "Envoie-moi une photo mystère à deviner.",
      "Envoie-moi un mini-jeu de mots avec mon prénom.",
      "Envoie-moi ta meilleure réplique de drague, même ratée.",
      "Envoie-moi une émotion en un mot qui te représente là.",
      "Envoie-moi une question coquine que tu meurs d'envie de me poser.",
      "Envoie-moi un défi que tu me lances en retour.",
      "Envoie-moi un indice sur ce que tu portes aujourd'hui."
    ]
  },
  {
    "id": 3,
    "name": "Charmeur",
    "desc": "Séduction assumée, encore tout public",
    "color": "#dba15c",
    "dares": [
      "Envoie un vocal où tu me dis ce que tu préfères chez moi physiquement.",
      "Envoie un vocal où tu me dis ce qui t'attire le plus chez moi.",
      "Envoie un vocal où tu me dis un mot doux que tu ne m'as jamais dit à voix haute.",
      "Envoie un vocal où tu me dis ce que tu penses de mon sourire.",
      "Envoie un vocal où tu me dis l'effet que je te fais quand on se parle.",
      "Envoie un vocal où tu me dis ce que tu ressens quand tu penses à moi le soir.",
      "Envoie un vocal où tu me dis un compliment sur ma voix.",
      "Envoie un vocal où tu me dis ce que tu aimerais me chuchoter à l'oreille.",
      "Envoie un vocal où tu me dis ce que tu ressens quand je te complimente.",
      "Envoie un vocal où tu me dis ce qui te manque le plus de moi en ce moment.",
      "Envoie un vocal où tu me dis ce que tu penses de notre alchimie.",
      "Envoie un vocal où tu me dis un mot doux, dit lentement.",
      "Décris la première chose que tu ferais si on se retrouvait dans 5 minutes.",
      "Décris la première chose que tu ferais si on se retrouvait dans une heure.",
      "Décris la première chose que tu ferais si on se retrouvait dans ce soir.",
      "Décris la première chose que tu ferais si on se retrouvait dans demain matin.",
      "Décris la première chose que tu ferais si on se retrouvait dans un week-end entier.",
      "Décris la première chose que tu ferais si on se retrouvait dans une semaine.",
      "Décris la première chose que tu ferais si on se retrouvait dans un an.",
      "Décris la première chose que tu ferais si on se retrouvait dans à l'improviste dans la rue.",
      "Décris la première chose que tu ferais si on se retrouvait dans après une longue absence.",
      "Décris la première chose que tu ferais si on se retrouvait dans au réveil.",
      "Décris la première chose que tu ferais si on se retrouvait dans en pleine nuit.",
      "Décris la première chose que tu ferais si on se retrouvait dans après une soirée entre amis.",
      "Envoie une photo de toi dans une tenue que tu sais que j'aime bien.",
      "Envoie une photo de toi dans ta tenue la plus confortable mais chic.",
      "Envoie une photo de toi dans un vêtement qui te met en valeur selon toi.",
      "Envoie une photo de toi dans ta tenue du soir idéale.",
      "Envoie une photo de toi dans quelque chose de simple mais élégant.",
      "Envoie une photo de toi dans ta tenue de rendez-vous préférée.",
      "Envoie une photo de toi dans un look que tu n'as jamais montré.",
      "Envoie une photo de toi dans ta tenue casual du dimanche.",
      "Envoie une photo de toi dans un accessoire que tu adores porter.",
      "Envoie une photo de toi dans ta tenue préférée pour te sentir bien.",
      "Envoie une photo de toi dans quelque chose de doux et confortable.",
      "Envoie une photo de toi dans ta tenue la plus « toi ».",
      "Raconte le rêve le plus romantique que tu as fait de nous deux.",
      "Raconte le rêve le plus romantique que tu as fait avec moi dedans.",
      "Raconte le rêve le plus romantique que tu as fait où on voyageait ensemble.",
      "Raconte le rêve le plus romantique que tu as fait où on vivait ensemble.",
      "Raconte le rêve le plus romantique que tu as fait où je te faisais une surprise.",
      "Raconte le rêve le plus romantique que tu as fait où on dansait tous les deux.",
      "Raconte le rêve le plus romantique que tu as fait où on se retrouvait après une longue attente.",
      "Raconte le rêve le plus romantique que tu as fait où on vieillissait ensemble.",
      "Raconte le rêve le plus romantique que tu as fait où tout était parfait entre nous.",
      "Raconte le rêve le plus romantique que tu as fait où je te disais quelque chose d'important.",
      "Raconte le rêve le plus romantique que tu as fait où on se mariait, même de façon absurde.",
      "Raconte le rêve le plus romantique que tu as fait où on regardait les étoiles ensemble.",
      "Envoie un vocal chuchoté avec un mot doux.",
      "Envoie un vocal chuchoté avec une pensée pour moi.",
      "Envoie un vocal chuchoté avec un secret tout léger.",
      "Envoie un vocal chuchoté avec trois mots qui me feraient rougir.",
      "Envoie un vocal chuchoté avec une promesse toute douce.",
      "Envoie un vocal chuchoté avec une phrase que tu gardais pour un moment comme celui-ci.",
      "Envoie un vocal chuchoté avec un compliment murmuré.",
      "Envoie un vocal chuchoté avec ce que tu ferais si j'étais juste à côté de toi.",
      "Envoie un vocal chuchoté avec une invitation douce pour ce soir.",
      "Envoie un vocal chuchoté avec un « tu me manques » sincère.",
      "Envoie un vocal chuchoté avec une déclaration courte mais vraie.",
      "Envoie un vocal chuchoté avec un mot inventé rien que pour nous.",
      "Décris en mots ton endroit préféré pour un câlin.",
      "Décris en mots la sensation d'être dans mes bras.",
      "Décris en mots ce que tu ressens quand on se tient la main.",
      "Décris en mots ton moment préféré de tendresse avec moi.",
      "Décris en mots l'endroit où tu voudrais qu'on s'embrasse.",
      "Décris en mots ce que tu ressens juste avant un baiser.",
      "Décris en mots la position que tu préfères pour un câlin.",
      "Décris en mots ce que tu aimes dans un moment de calme à deux.",
      "Décris en mots l'ambiance parfaite pour une soirée romantique.",
      "Décris en mots ce que tu ressens quand je te regarde dans les yeux.",
      "Décris en mots ton souvenir tactile préféré avec moi.",
      "Décris en mots ce que la tendresse représente pour toi.",
      "Envoie une photo avec ton regard le plus charmeur.",
      "Envoie une photo avec un sourire en coin.",
      "Envoie une photo avec une pose décontractée mais assumée.",
      "Envoie une photo avec ton expression la plus séduisante.",
      "Envoie une photo avec un jeu de lumière que tu aimes.",
      "Envoie une photo avec ton style le plus confiant.",
      "Envoie une photo avec un regard direct à la caméra.",
      "Envoie une photo avec une posture nonchalante.",
      "Envoie une photo avec ton attitude la plus sûre de toi.",
      "Envoie une photo avec un mini sourire mystérieux.",
      "Envoie une photo avec ton allure du soir.",
      "Envoie une photo avec ta meilleure version de toi ce soir.",
      "Raconte le moment où tu as su que tu craquais pour moi.",
      "Raconte le moment où tu as pensé à moi pour la première fois de façon différente.",
      "Raconte le moment où tu as ressenti un vrai frisson à cause de moi.",
      "Raconte le moment où tu as compris que ce n'était pas juste anodin entre nous.",
      "Raconte le moment où tu as eu envie de m'embrasser pour la première fois.",
      "Raconte le moment où tu as réalisé que je te plaisais vraiment.",
      "Raconte le moment où un simple message de moi t'a fait sourire toute la journée.",
      "Raconte le moment où tu as eu un coup de chaud en pensant à moi.",
      "Raconte le moment où tu as compris que tu voulais plus qu'une amitié.",
      "Raconte le moment où tu as eu envie de me le dire mais tu t'es retenu·e.",
      "Raconte le moment où tu as ressenti le plus de désir pour moi.",
      "Raconte le moment où tu as su que cette alchimie était différente des autres.",
      "Envoie-moi une lettre d'amour de 3 phrases, écrite maintenant.",
      "Envoie-moi une lettre d'amour de 4 phrases, sans réfléchir, écrite maintenant.",
      "Envoie-moi une lettre d'amour de 2 phrases, les plus sincères possible, écrite maintenant.",
      "Envoie-moi une lettre d'amour de 5 phrases, façon lettre ancienne, écrite maintenant.",
      "Envoie-moi une lettre d'amour de 3 phrases, avec un mot inventé pour nous, écrite maintenant.",
      "Envoie-moi une lettre d'amour de quelques lignes improvisées, écrite maintenant.",
      "Envoie-moi une lettre d'amour de 3 phrases qui commencent toutes par « Toi, », écrite maintenant.",
      "Envoie-moi une lettre d'amour de 3 phrases qui parlent de ce que je t'inspire, écrite maintenant.",
      "Envoie-moi une lettre d'amour de 3 phrases, façon poème, écrite maintenant.",
      "Envoie-moi une lettre d'amour de 3 phrases très directes, écrite maintenant.",
      "Envoie-moi une lettre d'amour de 3 phrases qui décrivent ton attirance pour moi, écrite maintenant.",
      "Envoie-moi une lettre d'amour de 3 phrases, comme si c'était la dernière que tu m'écrivais, écrite maintenant."
    ]
  },
  {
    "id": 4,
    "name": "Brûlant",
    "desc": "Ça chauffe — à faire si vous êtes tous les deux à l'aise",
    "color": "#cf6d5e",
    "dares": [
      "Envoie un vocal où tu me dis ce qui te manque le plus de moi physiquement.",
      "Envoie un vocal où tu me dis l'effet que te fait l'idée de ma présence tout près.",
      "Envoie un vocal où tu me dis ce que tu ressens quand tu imagines mes mains sur toi.",
      "Envoie un vocal où tu me dis ce que tu voudrais que je te fasse ressentir en premier.",
      "Envoie un vocal où tu me dis ce que tu ressens rien qu'en lisant ce message.",
      "Envoie un vocal où tu me dis un mot coquin à l'oreille.",
      "Envoie un vocal où tu me dis ce que tu ferais si j'étais allongé·e à côté de toi là.",
      "Envoie un vocal où tu me dis ce que ma voix te fait ressentir.",
      "Envoie un vocal où tu me dis ce que tu aimerais qu'on fasse ce soir, sans filtre.",
      "Envoie un vocal où tu me dis ce que tu ressens dans ton corps en pensant à moi.",
      "Envoie un vocal où tu me dis ton désir du moment, en toute honnêteté.",
      "Envoie un vocal où tu me dis ce que tu meurs d'envie de me chuchoter.",
      "Décris avec des mots ce que tu ferais en premier si on se retrouvait ce soir.",
      "Décris avec des mots ce que tu ferais en premier si j'étais devant ta porte là, maintenant.",
      "Décris avec des mots ce que tu ferais en premier si on avait toute la nuit devant nous.",
      "Décris avec des mots ce que tu ferais en premier si on se retrouvait après une longue attente.",
      "Décris avec des mots ce que tu ferais en premier si je t'attendais déjà dans le noir.",
      "Décris avec des mots ce que tu ferais en premier si on n'avait aucune limite de temps.",
      "Décris avec des mots ce que tu ferais en premier si j'arrivais chez toi sans prévenir.",
      "Décris avec des mots ce que tu ferais en premier si tu me retrouvais après une soirée.",
      "Décris avec des mots ce que tu ferais en premier si on se croisait seuls, sans personne autour.",
      "Décris avec des mots ce que tu ferais en premier si on avait toute une chambre d'hôtel pour nous.",
      "Décris avec des mots ce que tu ferais en premier si je te surprenais au réveil.",
      "Décris avec des mots ce que tu ferais en premier si on se retrouvait sous une pluie chaude d'été.",
      "Envoie une photo suggestive que tu es vraiment à l'aise de partager.",
      "Envoie une photo suggestive prise dans ta tenue de nuit.",
      "Envoie une photo suggestive qui montre ta silhouette, à ton rythme.",
      "Envoie une photo suggestive avec un jeu d'ombre et de lumière.",
      "Envoie une photo suggestive de ton dos ou de ta nuque.",
      "Envoie une photo suggestive qui laisse deviner plus qu'elle ne montre.",
      "Envoie une photo suggestive prise devant un miroir.",
      "Envoie une photo suggestive qui te fait te sentir désirable.",
      "Envoie une photo suggestive avec seulement une partie de ton visage visible.",
      "Envoie une photo suggestive qui joue avec un drap ou un vêtement large.",
      "Envoie une photo suggestive où tu te sens sexy sans en faire trop.",
      "Envoie une photo suggestive prise dans une lumière tamisée.",
      "Raconte un fantasme que tu n'as encore jamais partagé avec moi.",
      "Raconte un fantasme que tu gardes en tête depuis un moment.",
      "Raconte un fantasme qui implique un lieu précis.",
      "Raconte un fantasme qui te fait rougir rien que d'y penser.",
      "Raconte un fantasme que tu voudrais qu'on réalise un jour.",
      "Raconte un fantasme qui mélange tendresse et désir.",
      "Raconte un fantasme avec un scénario improbable mais excitant.",
      "Raconte un fantasme qui te trotte dans la tête depuis notre dernière conversation.",
      "Raconte un fantasme que tu n'as jamais osé dire à voix haute.",
      "Raconte un fantasme qui commence par une surprise.",
      "Raconte un fantasme qui se passe un soir de pluie.",
      "Raconte un fantasme que tu trouves un peu tabou mais que tu assumes.",
      "Envoie un vocal où tu me dis un mot un peu coquin à l'oreille.",
      "Envoie un vocal où tu me dis ce que tu ferais si j'étais tout contre toi à l'oreille.",
      "Envoie un vocal où tu me dis une promesse pour ce soir à l'oreille.",
      "Envoie un vocal où tu me dis ce que ta main ferait si elle était sur moi à l'oreille.",
      "Envoie un vocal où tu me dis une envie douce et joueuse à l'oreille.",
      "Envoie un vocal où tu me dis ce que tu ressens dans ce moment précis à l'oreille.",
      "Envoie un vocal où tu me dis une invitation sans détour à l'oreille.",
      "Envoie un vocal où tu me dis ce que tu voudrais entendre de ma part à l'oreille.",
      "Envoie un vocal où tu me dis trois mots qui te font frissonner à l'oreille.",
      "Envoie un vocal où tu me dis ce que tu imagines pour la suite de la soirée à l'oreille.",
      "Envoie un vocal où tu me dis une phrase qui te ressemble, sans filtre à l'oreille.",
      "Envoie un vocal où tu me dis ce que tu aimerais qu'on essaie ensemble à l'oreille.",
      "Décris la tenue que tu portes en ce moment, façon aguicheuse.",
      "Décris ce que tu porterais si j'arrivais dans 10 minutes, façon aguicheuse.",
      "Décris ta tenue de nuit préférée, façon aguicheuse.",
      "Décris le premier geste que tu ferais si on se retrouvait, façon aguicheuse.",
      "Décris un vêtement qui te fait te sentir irrésistible, façon aguicheuse.",
      "Décris ta tenue idéale pour une soirée juste nous deux, façon aguicheuse.",
      "Décris ce que tu voudrais que je te vois porter, façon aguicheuse.",
      "Décris l'ambiance de la pièce où tu es là, façon aguicheuse.",
      "Décris ta position favorite pour te détendre, en détail, façon aguicheuse.",
      "Décris ce que tu ressens contre ta peau là, façon aguicheuse.",
      "Décris l'odeur ou la texture de ce que tu portes, façon aguicheuse.",
      "Décris ta tenue si on improvisait une soirée à deux, façon aguicheuse.",
      "Raconte le compliment le plus osé que tu aies envie de me faire.",
      "Raconte ce que tu ressens en pensant à mon corps, sans filtre.",
      "Raconte le moment où le désir monte le plus vite pour toi.",
      "Raconte ce qui t'attire le plus chez moi physiquement.",
      "Raconte une scène que tu imagines entre nous ce soir.",
      "Raconte ce que tu ressens juste avant qu'on se touche.",
      "Raconte ta réaction si je te surprenais en pleine nuit.",
      "Raconte ce que tu aimerais qu'on chuchote l'un à l'autre.",
      "Raconte la dernière fois que tu as pensé à moi de façon intense.",
      "Raconte ce que ton corps te dit là, maintenant.",
      "Raconte ce que tu ressens en imaginant ma respiration près de la tienne.",
      "Raconte le geste que tu voudrais recevoir de moi en premier ce soir.",
      "Envoie une photo de ta main, prise sous un bon angle.",
      "Envoie une photo de ton bras, prise sous un bon angle.",
      "Envoie une photo de ton cou, prise sous un bon angle.",
      "Envoie une photo de tes lèvres, prise sous un bon angle.",
      "Envoie une photo de ton dos, prise sous un bon angle.",
      "Envoie une photo de ta clavicule, prise sous un bon angle.",
      "Envoie une photo de tes jambes, prise sous un bon angle.",
      "Envoie une photo de ton profil dans la pénombre, prise sous un bon angle.",
      "Envoie une photo de ta nuque dégagée, prise sous un bon angle.",
      "Envoie une photo de tes mains posées sur toi, prise sous un bon angle.",
      "Envoie une photo de un détail de ta peau que tu aimes, prise sous un bon angle.",
      "Envoie une photo de ton reflet dans un miroir, discret, prise sous un bon angle."
    ]
  },
  {
    "id": 5,
    "name": "Sans limites",
    "desc": "Le plus intense — honnêteté totale, désir assumé, à personnaliser à deux",
    "color": "#c65b6c",
    "dares": [
      "Décris en détail, avec des mots seulement, ce que tu ferais si j'étais avec toi ce soir, minute par minute.",
      "Décris en détail, avec des mots seulement, la première chose que tu murmurerais si on se retrouvait enfin.",
      "Décris en détail, avec des mots seulement, ce que tu ressens dans tout ton corps en lisant ce défi.",
      "Décris en détail, avec des mots seulement, la scène que tu imagines si on avait toute la nuit devant nous.",
      "Décris en détail, avec des mots seulement, ce que tu voudrais qu'on s'autorise, sans aucune limite.",
      "Décris en détail, avec des mots seulement, l'intensité de ce que tu ressens pour moi là, maintenant.",
      "Décris en détail, avec des mots seulement, ce que tu ferais si les mots n'avaient plus de limites entre nous.",
      "Décris en détail, avec des mots seulement, ce que ton corps réclame en ce moment précis.",
      "Décris en détail, avec des mots seulement, la tension que tu ressens en pensant à nous deux ce soir.",
      "Décris en détail, avec des mots seulement, ce que tu voudrais vivre avec moi, sans aucune retenue.",
      "Décris en détail, avec des mots seulement, le scénario le plus intense que tu oses imaginer entre nous.",
      "Décris en détail, avec des mots seulement, ce que tu ressens quand tu t'autorises à ne plus rien retenir.",
      "Décris en détail, avec des mots seulement, ce que tu ferais de moi si tu avais tous les droits ce soir.",
      "Envoie un vocal sans filtre où tu dis ce dont tu as vraiment envie ce soir.",
      "Envoie un vocal sans filtre où tu dis ce que tu ressens là, sans aucune retenue.",
      "Envoie un vocal sans filtre où tu dis ton désir le plus brut pour moi en ce moment.",
      "Envoie un vocal sans filtre où tu dis ce que tu voudrais que je fasse en premier.",
      "Envoie un vocal sans filtre où tu dis ce que tu meurs d'envie de vivre avec moi.",
      "Envoie un vocal sans filtre où tu dis ce que tu ressens rien qu'en pensant à nos corps l'un contre l'autre.",
      "Envoie un vocal sans filtre où tu dis ta vérité la plus crue sur ce que tu veux ce soir.",
      "Envoie un vocal sans filtre où tu dis ce que tu ressens dans ta poitrine en m'imaginant proche.",
      "Envoie un vocal sans filtre où tu dis ce que tu voudrais qu'on s'autorise cette nuit.",
      "Envoie un vocal sans filtre où tu dis ton envie la plus intense, sans détour.",
      "Envoie un vocal sans filtre où tu dis ce que tu ressens quand tu t'imagines totalement livré·e à moi.",
      "Envoie un vocal sans filtre où tu dis la chose que tu n'as jamais osé dire à voix haute jusqu'ici.",
      "Partage ton fantasme le plus intime, celui que tu gardes d'habitude pour toi.",
      "Partage le scénario qui te fait le plus perdre le contrôle, celui que tu gardes d'habitude pour toi.",
      "Partage le désir que tu n'avoues presque jamais, celui que tu gardes d'habitude pour toi.",
      "Partage ton envie la plus secrète à propos de nous, celui que tu gardes d'habitude pour toi.",
      "Partage le souvenir le plus intense que tu gardes de nous, celui que tu gardes d'habitude pour toi.",
      "Partage ta pensée la plus interdite du moment, celui que tu gardes d'habitude pour toi.",
      "Partage le rêve le plus brûlant que tu aies fait de nous, celui que tu gardes d'habitude pour toi.",
      "Partage ce que tu voudrais absolument essayer avec moi, celui que tu gardes d'habitude pour toi.",
      "Partage l'idée qui te trotte en tête depuis des jours, celui que tu gardes d'habitude pour toi.",
      "Partage ton scénario ultime, sans aucun tabou, celui que tu gardes d'habitude pour toi.",
      "Partage l'endroit le plus improbable où tu m'imagines, celui que tu gardes d'habitude pour toi.",
      "Partage ta version la plus honnête de ce que tu veux vraiment, celui que tu gardes d'habitude pour toi.",
      "Envoie la photo la plus intime que tu es prêt·e à envoyer, à ton rythme, sans pression.",
      "Envoie la photo la plus intime que tu es prêt·e à envoyer, dans la lumière que tu préfères.",
      "Envoie la photo la plus intime que tu es prêt·e à envoyer, en te sentant totalement toi-même.",
      "Envoie la photo la plus intime que tu es prêt·e à envoyer, avec seulement ce que tu es à l'aise de montrer.",
      "Envoie la photo la plus intime que tu es prêt·e à envoyer, juste pour ce moment entre nous.",
      "Envoie la photo la plus intime que tu es prêt·e à envoyer, sur un coup de tête, sans trop réfléchir.",
      "Envoie la photo la plus intime que tu es prêt·e à envoyer, comme un cadeau rien que pour moi.",
      "Envoie la photo la plus intime que tu es prêt·e à envoyer, dans le cadre où tu te sens le plus désirable.",
      "Envoie la photo la plus intime que tu es prêt·e à envoyer, avec la confiance que tu as en toi ce soir.",
      "Envoie la photo la plus intime que tu es prêt·e à envoyer, en gardant ce qui reste juste à toi.",
      "Envoie la photo la plus intime que tu es prêt·e à envoyer, à la seule condition que ça te fasse du bien.",
      "Envoie la photo la plus intime que tu es prêt·e à envoyer, comme une preuve de confiance entre nous.",
      "Décris minute par minute la soirée que tu imagines si on se retrouvait là, sans aucune limite.",
      "Décris minute par minute ce qui se passerait entre nous si personne ne nous voyait.",
      "Décris minute par minute la nuit la plus intense que tu oses imaginer avec moi.",
      "Décris minute par minute le scénario que tu rejoues le plus souvent dans ta tête.",
      "Décris minute par minute ce que tu ferais si tu avais un contrôle total sur cette soirée.",
      "Décris minute par minute la façon dont tu voudrais que la nuit commence, et se termine.",
      "Décris minute par minute un rendez-vous sans aucune règle entre nous.",
      "Décris minute par minute ce qui arriverait si on se laissait aller complètement.",
      "Décris minute par minute la soirée parfaite selon ton désir le plus honnête.",
      "Décris minute par minute ce que tu ferais si tu n'avais plus aucune pudeur avec moi.",
      "Décris minute par minute le moment où tout basculerait entre nous ce soir-là.",
      "Décris minute par minute ta version la plus intense d'une nuit ensemble.",
      "Réponds honnêtement : quelle est la chose que tu meurs d'envie qu'on fasse ensemble bientôt ?",
      "Réponds honnêtement : qu'est-ce que tu attends le plus de notre prochaine rencontre ?",
      "Réponds honnêtement : quel est ton plus grand désir inavoué à propos de nous ?",
      "Réponds honnêtement : jusqu'où voudrais-tu qu'on aille cette fois ?",
      "Réponds honnêtement : qu'est-ce qui te ferait complètement perdre pied avec moi ?",
      "Réponds honnêtement : quelle limite aimerais-tu qu'on repousse ensemble ?",
      "Réponds honnêtement : quel est le scénario que tu espères secrètement vivre avec moi ?",
      "Réponds honnêtement : qu'est-ce que tu voudrais que je devine sans que tu le dises ?",
      "Réponds honnêtement : quelle est la chose la plus folle que tu ferais pour moi ce soir ?",
      "Réponds honnêtement : qu'est-ce que tu ressens quand tu t'imagines totalement libre avec moi ?",
      "Réponds honnêtement : quelle question n'as-tu jamais osé me poser ?",
      "Réponds honnêtement : qu'est-ce que tu voudrais qu'on s'autorise, juste cette fois ?"
    ]
  }
];
